name: "SimpleMarkdownAction"
on: 
    schedule:
      - cron: 0 9 * * 6
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: SimpleMarkdownAction
        uses: ./
        with:
          directory: "templates"
          template: "contents.md"
          output: "README.md"
          title: "Awesome List"